runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: dist/cotw-angular/index.html
  upload: dist/cotw-angular/index.html

- url: /(.*)
  static_files: dist/cotw-angular/\1
  upload: dist/cotw-angular/(.*)
